package(default_visibility = ["//visibility:public"])

java_library(
    name = "ProjectLibs",
    srcs = glob(["**/*.java"]),
    deps = [
        #"//port:main",
        #"//dockerized/common:main",
        #"//dockerized/sql_server:main",
        #"//fire:main",
        "@maven//:com_amazonaws_aws_java_sdk_core",
        "@maven//:com_amazonaws_aws_java_sdk_s3",
        "@maven//:com_fasterxml_jackson_core_jackson_annotations",
        "@maven//:com_fasterxml_jackson_core_jackson_databind",
        "@maven//:com_fasterxml_jackson_datatype_jackson_datatype_jdk8",
        "@maven//:com_google_guava_guava",
        "@maven//:com_microsoft_sqlserver_mssql_jdbc",
        "@maven//:com_oracle_database_jdbc_ojdbc8_production",
        "@maven//:commons_codec_commons_codec",
        "@maven//:io_micrometer_micrometer_core",
        "@maven//:io_netty_netty_buffer",
        "@maven//:io_opentelemetry_opentelemetry_api",
        "@maven//:io_opentelemetry_opentelemetry_extension_annotations",
        "@maven//:javax_annotation_javax_annotation_api",
        "@maven//:junit_junit",
        "@maven//:net_snowflake_snowflake_jdbc",
        "@maven//:org_apache_commons_commons_lang3",
        "@maven//:org_awaitility_awaitility",
        "@maven//:org_json_json",
        "@maven//:org_apache_velocity_velocity",
        "@maven//:commons_collections_commons_collections"
    ],
)
